name: 🧪 Test Coverage
on: [push]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout Repo
        uses: actions/checkout@v2

      - name: 🥯 Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 📦 Install Dependencies
        run: bun install

      - name: 🧪 Run Test Coverage
        run: bun test --coverage
